export const teamLogos = {
  "Arizona Diamondbacks": "https://www.mlbstatic.com/team-logos/109.svg",
  "Atlanta Braves": "https://www.mlbstatic.com/team-logos/144.svg",
  "Baltimore Orioles": "https://www.mlbstatic.com/team-logos/110.svg",
  "Boston Red Sox": "https://www.mlbstatic.com/team-logos/111.svg",
  "Chicago Cubs": "https://www.mlbstatic.com/team-logos/112.svg",
  "Chicago White Sox": "https://www.mlbstatic.com/team-logos/145.svg",
  "Cincinnati Reds": "https://www.mlbstatic.com/team-logos/113.svg",
  "Cleveland Guardians": "https://www.mlbstatic.com/team-logos/114.svg",
  "Colorado Rockies": "https://www.mlbstatic.com/team-logos/115.svg",
  "Detroit Tigers": "https://www.mlbstatic.com/team-logos/116.svg",
  "Houston Astros": "https://www.mlbstatic.com/team-logos/117.svg",
  "Kansas City Royals": "https://www.mlbstatic.com/team-logos/118.svg",
  "Los Angeles Angels": "https://www.mlbstatic.com/team-logos/108.svg",
  "Los Angeles Dodgers": "https://www.mlbstatic.com/team-logos/119.svg",
  "Miami Marlins": "https://www.mlbstatic.com/team-logos/146.svg",
  "Milwaukee Brewers": "https://www.mlbstatic.com/team-logos/158.svg",
  "Minnesota Twins": "https://www.mlbstatic.com/team-logos/142.svg",
  "New York Mets": "https://www.mlbstatic.com/team-logos/121.svg",
  "New York Yankees": "https://www.mlbstatic.com/team-logos/147.svg",
  "Oakland Athletics": "https://www.mlbstatic.com/team-logos/133.svg",
  "Philadelphia Phillies": "https://www.mlbstatic.com/team-logos/143.svg",
  "Pittsburgh Pirates": "https://www.mlbstatic.com/team-logos/134.svg",
  "San Diego Padres": "https://www.mlbstatic.com/team-logos/135.svg",
  "San Francisco Giants": "https://www.mlbstatic.com/team-logos/137.svg",
  "Seattle Mariners": "https://www.mlbstatic.com/team-logos/136.svg",
  "St. Louis Cardinals": "https://www.mlbstatic.com/team-logos/138.svg",
  "Tampa Bay Rays": "https://www.mlbstatic.com/team-logos/139.svg",
  "Texas Rangers": "https://www.mlbstatic.com/team-logos/140.svg",
  "Toronto Blue Jays": "https://www.mlbstatic.com/team-logos/141.svg",
  "Washington Nationals": "https://www.mlbstatic.com/team-logos/120.svg"
};
